### ISSUE TITLE
Add weapon d'snt work

### ISSUE THREAD

**Issue by anatsvit** [IGI-Research-Devs/I.G.I-1-Editor#1]
ParseObjects(): Exception: System.FormatException: The input string had an invalid format.
in System.Number.parseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
in System.Double.Parse(String s)
in IGIEditor.qutils.ParseObjects(String cdata)

**Comment by IGI-Research-Devs** [comment]
Thanks I will look about that issue.

**Comment by IGI-Research-Devs** [comment]
Looks like editor having issues with Local language localization so best thing you can do it switch system **language to English**.
